name: 检查直播状态
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-live:
    runs-on: ubuntu-latest
    steps:

      #1
      - name: 检出仓库代码
      uses: actions/checkout@v4

      #2
      - name: 安装chrome浏览器
        run: |
            sudo apt update
            sudo apt install -y chromium-browser chromium-chromedriver
            # 配置Chrome路径
            export CHROME_BIN=/usr/bin/chromium-browser
            export CHROME_DRIVER=/usr/bin/chromedriver

       # 3
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      # 4
      - name: 安装依赖包
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 selenium webdriver-manager

      # 5
      - name: 运行直播检查脚本
        run: python check_live.py